### ISSUE TITLE
Add link on the logo to homepage

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/lka#4]
Add a link on to the LKA logo in the header to the homepage.

**Comment by ericsheng495** [comment]
First used the normal website link (<a href="http://home.com" id="logo">Your logo</a>) , however, it was too slow to refresh. So, I implemented the angular routing link to increase the speed(  <a routerLink="/home"><img src="assets/LKA.png" align="left" class="logo"></a>).
