### ISSUE TITLE
Navigation Bar Design

### ISSUE THREAD

**Issue by toliujiayi** [hicodingclub/lka#8]
Find out the different navigation bar items the website needs

**Comment by ericsheng495** [comment]
I added new items to the navigation bar: classes, teachers, courses and FAQ.

**Comment by ericsheng495** [comment]
![zv5nhwqjsbgha5jlaz5t7g](https://user-images.githubusercontent.com/44331935/52530342-bbed3380-2cb8-11e9-950b-759ced447658.jpg)
